env = Environment()

env['APP_TARGET'] = 'KinectPointCloudGLApp'
env['APP_SOURCES'] = ['KinectPointCloudGLApp.cpp']
env['ASSETS'] = ['*.glsl']

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
