env = Environment()

env['APP_TARGET'] = 'KinectBasicApp'
env['APP_SOURCES'] = ['KinectBasicApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
