Import('env')

_INCLUDES = [Dir('../src').abspath, Dir('../src/freenect').abspath]

_SOURCES = ['CinderFreenect.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]
_SOURCES_FREENECT = ['cameras.c', 'core.c', 'flags.c', 'registration.c', 'tilt.c', 'usb_libusb10.c']
_SOURCES_FREENECT = [File('../src/freenect/' + s).abspath for s in _SOURCES_FREENECT]
_SOURCES += _SOURCES_FREENECT

_LIBS = ['libusb-1.0.a']
if env['PLATFORM'] == 'darwin':
	_LIBS = [Dir('../lib/macosx/').abspath + '/' + s for s in _LIBS]
else:
	_LIBS = []

_LIBS = [File(s) for s in _LIBS]

env.Append(APP_SOURCES = _SOURCES)
env.Append(CPPPATH = _INCLUDES)
env.Append(LIBS = _LIBS)
if env['PLATFORM'] == 'darwin':
	env.Append(FRAMEWORKS = ['IOKit'])

Return('env')
